modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = ""

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "cleannrooster"
description = '''
Divine Bosses and Divine Encounters
'''
logoFile = "assets/divine_encounters/icon.png"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "architectury"
type = "required"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "geckolib"
type = "required"
versionRange = "[4.8,)"
ordering = "AFTER"
side = "BOTH"
